name: Build the Qt SDK

on: workflow_dispatch

jobs:
  Windows:
    runs-on: windows-latest

    steps:
    - name: Check out the repository code
      uses: actions/checkout@v3

    - name: Set up GIT
      run: call windows-git.bat
      shell: cmd

    - name: Set up Vulkan SDK (QtGui)
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.224.1 # Current latest version.
        vulkan-components: Vulkan-Headers

    - name: Set up VCPKG (QtBase)
      run: call windows-vcpkg.bat
      shell: cmd

    - name: Build the Qt Toolkit
      run: call windows-build.bat
      shell: cmd

    - name: Pack the installed artifacts
      run: call windows-pack.bat
      shell: cmd

    - name: Upload the final packages
      uses: actions/upload-artifact@v3
      with:
        name: Qt SDK
        path: build/windows/*.7z
