name: Build the Qt SDK

on: workflow_dispatch

jobs:
  Windows:
    runs-on: windows-latest

    steps:
    - name: Check out the repository code
      run: |
          cd /d C:
          md GitHub_Actions
          cd GitHub_Actions
          git clone --recurse-submodules --depth 1 --shallow-submodules --branch main --single-branch --no-tags --progress --verbose https://github.com/wangwenx190/build-qt-dev.git
      shell: cmd

    - name: Set up GIT
      working-directory: C:/GitHub_Actions/build-qt-dev
      run: call C:/GitHub_Actions/build-qt-dev/windows-git.bat
      shell: cmd

    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: |
          C:/Program Files/LLVM
          ./llvm
        key: llvm-15.0.1

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15.0.1"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'

    - name: Set up Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1
      with:
        vulkan-query-version: 1.3.224.1 # Current latest version.
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - name: Set up VCPKG
      working-directory: C:/GitHub_Actions/build-qt-dev
      run: call C:/GitHub_Actions/build-qt-dev/windows-vcpkg.bat
      shell: cmd

    - name: Build the Qt Toolkit
      working-directory: C:/GitHub_Actions/build-qt-dev
      run: call C:/GitHub_Actions/build-qt-dev/windows-build.bat
      shell: cmd

    - name: Pack the installed artifacts
      working-directory: C:/GitHub_Actions/build-qt-dev
      run: call C:/GitHub_Actions/build-qt-dev/windows-pack.bat
      shell: cmd

    - name: Upload the final packages
      uses: actions/upload-artifact@v3
      with:
        name: Qt SDK
        path: C:/GitHub_Actions/build-qt-dev/build/windows/*.7z
