name: Build the Qt SDK

on: workflow_dispatch

jobs:
  Windows:
    runs-on: windows-latest

    steps:
    - name: Check out the repository code
      uses: actions/checkout@v3

    - name: Build the Qt Toolkit
      run: call windows-build.bat

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Qt SDK
        path: build/windows/*.7z
