name: Build the Qt SDK

on: workflow_dispatch

jobs:
  Windows:
    runs-on: windows-latest

    steps:
    - name: Check out the repository code
      run: |
          cd /d C:
          md GitHub_Actions
          cd GitHub_Actions
          git clone --recurse-submodules --depth 1 --shallow-submodules --branch main --single-branch --no-tags --progress --verbose https://github.com/wangwenx190/build-qt-dev.git
      shell: cmd

    - name: Set up GIT
      working-directory: C:/GitHub_Actions/build-qt-dev
      run: call C:/GitHub_Actions/build-qt-dev/windows-git.bat
      shell: cmd

    - name: Set up LLVM
      working-directory: C:/GitHub_Actions/build-qt-dev
      run: call C:/GitHub_Actions/build-qt-dev/windows-llvm.bat
      shell: cmd

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1
      with:
        version: latest

    - name: Download custom patches
      working-directory: C:/GitHub_Actions/build-qt-dev
      run: call C:/GitHub_Actions/build-qt-dev/windows-download-patches.bat
      shell: cmd

    - name: Set up VCPKG
      working-directory: C:/GitHub_Actions/build-qt-dev
      run: call C:/GitHub_Actions/build-qt-dev/windows-vcpkg.bat
      shell: cmd

    - name: Set up VC-LTL
      working-directory: C:/GitHub_Actions/build-qt-dev
      run: call C:/GitHub_Actions/build-qt-dev/windows-vcltl.bat
      shell: cmd

    - name: Set up YY-Thunks
      working-directory: C:/GitHub_Actions/build-qt-dev
      run: call C:/GitHub_Actions/build-qt-dev/windows-yythunks.bat
      shell: cmd

    - name: Build the Qt Toolkit
      working-directory: C:/GitHub_Actions/build-qt-dev
      run: call C:/GitHub_Actions/build-qt-dev/windows-build.bat
      shell: cmd

    - name: Pack the installed artifacts
      working-directory: C:/GitHub_Actions/build-qt-dev
      run: call C:/GitHub_Actions/build-qt-dev/windows-pack.bat
      shell: cmd

    - name: Upload the final packages
      uses: actions/upload-artifact@v3
      with:
        name: Qt SDK
        path: C:/GitHub_Actions/build-qt-dev/build/windows/*.7z
