name: Build the Qt SDK

on: workflow_dispatch

jobs:
  Windows:
    runs-on: windows-latest

    steps:
    - name: Check out the repository code
      uses: actions/checkout@v3

    - name: Set up GIT
      run: call windows-git.bat
      shell: cmd

    - name: Set up VCPKG (QtBase)
      run: call windows-vcpkg.bat
      shell: cmd

    - name: Set up Vulkan SDK (QtGui)
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.216.0 # Current latest version.
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - name: Set up Node.js (QtWebEngine & QtPDF)
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Set up Python (QtWebEngine & QtPDF)
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.5' # Current latest version.

    - name: Build the Qt Toolkit
      run: call windows-build.bat
      shell: cmd

    - name: Pack the installed artifacts
      run: call windows-pack.bat
      shell: cmd

    - name: Upload the final packages
      uses: actions/upload-artifact@v3
      with:
        name: Qt SDK
        path: build/windows/*.7z
